name: Rust_MIRAI

on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  install_and_run_MIRAI:

    runs-on: ubuntu-latest

    steps:
    - name: Obtain base SHA
      id: sha_step
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        result-encoding: string
        script: |
          const commits = await github.pulls.listCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          });
          console.log(commits);
          const commit_ref = commits.data[0].sha;
          const commit = await github.repos.getCommit({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: commit_ref
          });
          console.log(commit);
          return commit.data.parents[0].sha;
    - name:
      env: 
        SHA: ${{ steps.sha_step.outputs.result }}
      run: echo $SHA
