name: Rust_MIRAI

on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  install_and_run_MIRAI:

    runs-on: ubuntu-latest

    steps:
    - name: Obtain base SHA
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        result-encoding: string
        script: |
          console.log(context)
          const commits = await context.github.pullRequests.listCommits(context.repo({number: pr_number}));
          const commit_ref = commits.data[0].sha;
          const commit = await context.github.repos.getCommit(context.repo({sha: commit_ref}));
          return commit.data.parents[0].sha;
    - name:
      env: 
        SHA: steps.1.outputs.result
      run: echo $SHA
