name: Rust_MIRAI

# Why `on: repository_dispatch`?
#
# If we trigger this action on pull_request events,
# then it will run with the forked repo GITHUB_TOKEN
# this is a problem as it won't allow the action to write 
# a comment on the PR in the last step.
#
# instead, we trigger this remotely via a bot we're running ourselves.
on: repository_dispatch

jobs:
  test_failure:

    runs-on: ubuntu-latest

    steps:
    - name: fails
      run: exit 1
