name: Rust

on: 
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  install_and_run_MIRAI:

    runs-on: ubuntu-latest

    steps:
    - name: Echo
      run: echo "prout" > mirai_results
    - name: Post Comment
      if: success()
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs');
          fs.readFile('mirai_results', 'utf-8', (err, data) => {
            console.log("err:", err);
            console.log("data:", data);
            github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: data
            });
          });
